---

#
# This file contains configuration flags to customize this site
#

# Name of the site (displayed in the content)
name: The Northstar✨ System & Co.
# Name of the site (displayed in the tab)
title: Northstar✨ & more

# Short bio or description (in share links)
description: "We are The Northstar System, The Harmonic System, & others in Ky: a few dozen people sharing the same body"


brand:
    name: The Northstar✨ System & Co.
    color:
        primary: "#1E007C"
    logo:
        monochrome:
            darkMode:
                - /images/Northstar-System-logo.2.0.0.monochrome.transparent.dark-mode.svg
                - /images/Northstar-System-logo.2.0.0.monochrome.transparent.dark-mode.webp
                - /images/Northstar-System-logo.2.0.0.monochrome.transparent.dark-mode.png

social:
    default-username: Supuhstar
    email: Hi@Supuhstar.com
    github: Supuhstar/Supuhstar.com
    bsky: Supuhstar.com
    telegram: Supuhstar
    mastodon:
        instance: mastodon.social
        username: Supuhstar
    tumblr: Supuhstar

authors:
    -
        role: Primary
        name: The Northstar✨ System
        shortName: North
        tagline-html: Many friends in one!
        avatar: https://gravatar.com/avatar/ce22034b5c562ac32304f60c3e86a7c5?size=512
        
        plurality: Plural
        
        social:
            blog: https://TODO-unnamed-blog.Supuhstar.com
            email: North@Supuhstar.com
            github-suffix:
                this: Supuhstar/Supuhstar.com
                personal: Supuhstar
            website: https://Supuhstar.com

dates:
    launch: 2025-01-14
    newest:
        web: 2025-01-14


introAnimationDuration: 4

default-theme:
    color: air
    brightness: dark
    
commonPages:
    about: /About

sidebar:
    headerImage:
        picture:
            sources:
                - /images/Northstar System Brand Header • Full Bleed (16-9) @486p.webp
                - /images/Northstar System Brand Header • Full Bleed (16-9) @486p.jpg
            alt: "Northstar System"
    
    aboutLink:
        label: About Us
        url: /About
    
    defaultLinks:
        -
            url: /Headmates
            text: Headmates list
        # -
        #     url: https://Blog.Supuhstar.com
        #     text: Blog


commonPages:
    about: About



# Site system info #

notableSystemIds:
    primarySystem: "zrbcSaxPS+y5kLFDFrEVcQ"
    hostSubsystem: "aHAMEKIHRwC18C0BmGYBEw"



# URLs #

# Used for Sitemap.xml and the RSS feed
url: https://Supuhstar.com

# Jekyll needs this if you're gonna be weird with SSH keys, and We are
repository: Supuhstar/Supuhstar.com

source-code:
    url: https://github.com/Supuhstar/Supuhstar.com
    productionBranchName: production
    issuesSubpath: issues/new
    eachPage:
        historySubpathPrefix: commits
        editSubpathPrefix: edit
    


timezone: America/Denver



# Low-level config lines #

#permalink: `/:title/`, `pretty`, etc.
permalink: /:title/

# The release of Jekyll that this site is using
version: v3.8.5

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
    # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
    style: :expanded  # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
    - jekyll-sitemap  # Create a sitemap using the official Jekyll sitemap gem
    - jekyll-feed  # Create an Atom feed using the official Jekyll feed gem
    - jekyll-archives
    - jekyll-redirect-from  # Allow multiple names for a page
whitelist: # allow these (apparently listing it as required ain't enough for it to actually work)
    - jekyll-redirect-from

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - CNAME
